[settings]
idiomatic_version_file_enable_tools = ['node', 'ruby']

[tasks.herdr-setup]
run = [
  'herdr plugin install cloudmanic/herdr-plus --yes',
  'npx skills add ogulcancelik/herdr --skill herdr -g --yes',
]

[tasks.opencode-setup]
depends = 'herdr-setup'
run = [
  'herdr integration install opencode',
]

[tasks.pi-setup]
depends = 'herdr-setup'
run = [
  'herdr integration install pi',
  'pi install npm:@gotgenes/pi-permission-system',
  'pi install npm:@gotgenes/pi-subagents',
]

[tasks.agent-setup]
description = 'Run all agent setups'
depends = ['opencode-setup', 'pi-setup']

[tools]
## Binaries and TUIs
atuin       = 'latest'
bat         = 'latest'
bottom      = 'latest'
codex       = 'latest'
delta       = 'latest'
direnv      = 'latest'
eza         = 'latest'
fd          = 'latest'
fzf         = 'latest'
github-cli  = 'latest'
herdr       = 'latest'
jq          = 'latest'
just        = 'latest'
lazydocker  = 'latest'
lazygit     = 'latest'
neovim      = 'stable'
opencode    = 'latest'
pi          = 'latest'
resvg       = 'latest'
ripgrep     = 'latest'
starship    = 'latest'
television  = 'latest'
tree-sitter = 'latest'
yazi        = 'latest'
zellij      = 'latest'
zoxide      = 'latest'

'github:rgwood/systemctl-tui' = { version = 'latest', os = ['linux'] }

## Languages
node   = 'lts'
python = 'latest'

## LSPs
marksman = 'latest'
