[tools]
# Languages
node = 'lts'
python = '3.12'
ruby = '3.3'
go = '1.22'

# Tools
bat = 'latest'
eza = 'latest'
fzf = 'latest'
github-cli = 'latest'
lazygit = 'latest'
neovim = 'stable'
ripgrep = 'latest'
tmux = 'latest'
tree-sitter = 'latest'
zoxide = 'latest'
