#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

audio_pkgs=(
  alsa-firmware
  alsa-plugins
  alsa-utils
  lib32-pipewire
  lib32-pipewire-jack
  lib32-pipewire-alsa
  lib32-pipewire-pulse
  lib32-openal
  lib32-libpulse
  libpulse
  pamixer
  pasystray
  pipewire
  pipewire-alsa
  pipewire-pulse
  pipewire-jack
  pulsemixer
  sof-firmware
  wireplumber
)

echo "Installing audio libraries and tools..."
paru -S --noconfirm --needed --quiet "${audio_pkgs[@]}"
