#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

echo "Installing Bluetooth packages..."
paru -S --noconfirm --needed --quiet bluetui bluez bluez-utils

echo "Enabling Bluetooth service..."
sudo systemctl enable --now bluetooth
