#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru.sh
fi

codecs=(
  ffmpeg
  gst-libav
  gst-plugin-pipewire
  gst-plugins-bad
  gst-plugins-base
  gst-plugins-good
  gst-plugins-ugly
  opus-tools
  vorbis-tools
)

echo "Installing multimedia codecs..."
paru -S --noconfirm --needed --quiet "${codecs[@]}"
