#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

echo "Installing Docker packages..."
paru -S --noconfirm --needed docker docker-buildx docker-compose

echo "Enabling Docker service..."
sudo systemctl enable --now docker

if ! groups $USER | grep -qw docker; then
  sudo usermod -aG docker $USER
  echo "You have been added to the docker group. Please log out and log back in for changes to take effect."
fi
