#! /usr/bin/env bash

sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed docker docker-buildx docker-compose

sudo systemctl enable --now docker

sudo usermod -aG docker $USER

newgrp docker
