#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru.sh
fi

paru -S --noconfirm --needed --quiet lshw jq

vendor_check=$(sudo lshw -json -c display | jq '.[0]["vendor"]')

base_drivers=(mesa lib32-mesa libva-utils)
amd_extra=(vulkan-radeon lib32-vulkan-radeon)
intel_extra=(vulkan-intel lib32-vulkan-intel intel-media-driver)

if [[ $vendor_check == *"Advanced Micro Devices"* ]]; then
  echo "Installing AMD drivers..."
  paru -S --noconfirm --needed --quiet "${base_drivers[@]}" "${amd_extra[@]}"
elif [[ $vendor_check == *"Intel"* ]]; then
  echo "Installing Intel drivers..."
  paru -S --noconfirm --needed --quiet "${base_drivers[@]}" "${intel_extra[@]}"
else
  paru -S --noconfirm --needed --quiet "${base_drivers[@]}"
fi
