#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

echo "Setting up flatpak and flathub repositories"
paru -S --noconfirm --needed --quiet flatpak

flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak_system_pkgs=(
  com.brave.Browser
  com.github.tchx84.Flatseal
  io.github.flattool.Warehouse
  io.missioncenter.MissionCenter
  one.ablaze.floorp
)

echo "Installing flatpak packages"
flatpak install -y --system "${flatpak_system_pkgs[@]}"

