#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru.sh
fi

fonts_pkgs=(
  nerd-fonts
  noto-fonts
  noto-fonts-cjk
  noto-fonts-emoji
  ttf-ms-fonts
)

echo "Installing font packages..."
paru -S --noconfirm --needed --quiet "${fonts_pkgs[@]}"
