#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

gnome_pkgs=(
  gdm
  gnome-control-center
  gnome-shell
  gnome-shell-extensions
  gnome-shell-extension-appindicator
  gnome-shell-extension-arc-menu
  gnome-shell-extension-dash-to-panel
  gnome-shell-extension-vitals
  gnome-shell-extension-weather-oclock
  gnome-tuner
  gnome-tuner-gdm
  gnome-tuner-panel
  gnome-tuner-tweaks
)

echo "Installing Gnome Shell packages..."
paru -S --noconfirm --needed --quiet "${gnome_pkgs[@]}"

sudo systemctl enable gdm

# Ensure default flatpaks are set up
bash $HOME/.dotfiles/dot-local/installers/arch/flatpak

gnome_flatpaks=(
  com.mattjakeman.ExtensionManager
  io.github.celluloid_player.Celluloid
  org.gnome.Loupe
  org.gnome.Papers
  org.gnome.SimpleScan
  org.gnome.Weather
)

flatpak install -y --system "${gnome_flatpaks[@]}"
