#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

icon_pkgs=(
  papirus-icon-theme
)

echo "Installing icon sets..."
paru -S --noconfirm --needed --quiet "${icon_pkgs[@]}"
