#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

niri_pkgs=(
  ghostty
  gnome-keyring
  mako
  mpd
  mpv
  ncmpcpp
  niri
  polkit-gnome
  swaybg
  swayidle
  swaylock
  udiskie
  waybar
  wofi
  wl-clipboard
  xdg-desktop-portal
  xdg-desktop-portal-gtk
  xdg-user-dirs-gtk
  xwayland-satellite
)

echo "Installing Niri environment packages..."
paru -S --noconfirm --needed --quiet "${niri_pkgs[@]}"
