#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

niri_pkgs=(
  cliphist
  fuzzel
  ghostty
  gnome-keyring
  gvfs
  gvfs-dnssd
  gvfs-gphoto2
  gvfs-mtp
  gvfs-nfs
  gvfs-smb
  mako
  mpd
  mpv
  nautilus
  ncmpcpp
  niri
  soteria-git
  swaybg
  swayidle
  swaylock
  waybar
  waypaper
  wiremix
  wl-clipboard
  xdg-desktop-portal
  xdg-desktop-portal-gtk
  xdg-desktop-portal-gnome
  xdg-user-dirs-gtk
  xwayland-satellite
)

echo "Installing Niri environment packages..."
paru -S --noconfirm --needed --quiet "${niri_pkgs[@]}"

echo "Setting up services..."
systemctl --user daemon-reload
systemctl --user add-wants niri.service cliphist.service
systemctl --user add-wants niri.service gnome-keyring-daemon.service
systemctl --user add-wants niri.service mako.service
systemctl --user add-wants niri.service mpd.service
systemctl --user add-wants niri.service soteria.service
systemctl --user add-wants niri.service waybar.service

