#! /usr/bin/env bash

sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed bat devtools

mkdir tmp
cd tmp

git clone https://aur.archlinux.org/paru-bin
cd paru-bin
makepkg -si

cd ../..
rm -rf tmp
