#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

printer_pkgs=(
  avahi
  cups
  cups-filters
  cups-pdf
  nss-mdns
  ghostscript
  gutenprint
  foomatic-db-gutenprint-ppds
  foomatic-db-engine
  foomatic-db
  foomatic-db-ppds
  foomatic-db-nonfree
  foomatic-db-nonfree-ppds
  sane
  sane-airscan
)

echo "Installing printer packages..."
paru -S --noconfirm --needed --quiet "${printer_pkgs[@]}"

# Update /etc/nsswitch.conf for Avahi hostname resolution
if ! grep -qe "hosts:.*mdns_minimal" /etc/nsswitch.conf; then
  echo "Configuring /etc/nsswitch.conf for Avahi hostname resolution..."
  sudo sed -i '/^hosts:/ s/$/ mdns_minimal [NOTFOUND=return]/' /etc/nsswitch.conf
fi

echo "Enabling printer services..."
sudo systemctl enable --now avahi-daemon
sudo systemctl enable --now cups
sudo systemctl enable --now cups-browsed
