#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

snapper_pkgs=(
  snapper
  snap-pac
)

echo "Installing Snapper and related packages..."
paru -S --noconfirm --needed --quiet "${snapper_pkgs[@]}"

echo "Configuring Snapper root subvolume..."
sudo umount /.snapshots 2>/dev/null || true
sudo rm -rf /.snapshots
sudo snapper -c root create-config /
sudo btrfs subvolume delete /.snapshots 2>/dev/null || true
sudo mkdir /.snapshots
sudo chmod 750 /.snapshots
sudo chown :wheel /.snapshots
sudo mount -a

if command -v grub-mkconfig &> /dev/null; then
  echo "Configuring grub-btrfs integration..."
  paru -S --noconfirm --needed --quiet grub-btrfs inotify-tools

  sudo systemctl enable --now grub-btrfsd
  sudo grub-mkconfig -o /boot/grub/grub.cfg
fi
