#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

steam_pkgs=(
  gamemode
  gamescope
  lib32-gamemode
  lib32-vulkan-icd-loader
  lib32-vulkan-intel
  lib32-vulkan-radeon
  mangohud
  steam
  vulkan-icd-loader
  vulkan-intel
  vulkan-radeon
)

echo "Installing Steam and gaming packages..."
paru -S --noconfirm --needed --quiet "${steam_pkgs[@]}"
