#! /usr/bin/env bash

sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed aws-cli bash-completion bat bat-extras bottom cabextract curl direnv eza fd fzf git git-delta github-cli gitui glow jq just lazygit lsd neovim p7zip poppler ripgrep starship tmux tree-sitter udiskie unace unrar unzip wget xz yazi yt-dlp zellij zoxide
