#! /usr/bin/env bash

if ! command -v paru &> /dev/null; then
  bash $HOME/.dotfiles/dot-local/installers/arch/paru
fi

echo "Installing zram-generator..."
paru -S --noconfirm --needed --quiet zram-generator

echo "Configuring zram-generator..."
sudo tee /etc/systemd/zram-generator.conf > /dev/null <<EOF
[zram0]
zram-size = min(ram / 2, 4096)
compression-algorithm = zstd
EOF

echo "Enabling zram swap..."
sudo systemctl enable --now systemd-zram-setup@zram0.service
