#!/bin/bash

OS=$(uname)

if [[ "$OS" = "Darwin" ]]; then
  if [[ ! -x "$(command -v apt)" ]]; then
    xcode-select --install
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  fi

  brew install openssl@3 readline libyaml gmp
elif [[ "$OS" = "Linux" ]]; then
  # Check Package Managers and install Deps
  if [[ -x "$(command -v apt)" ]]; then
    sudo apt install autoconf patch build-essential gawk git stow rustc libssl-dev libyaml-dev libreadline-dev zlib1g-dev libgmp-dev libncurses-dev libffi-dev libgdbm6t64 libgdbm-dev libdb-dev uuid-dev
  elif [[ -x "$(command -v dnf)" ]]; then
    sudo dnf group install c-development development-tools
    sudo dnf install -y autoconf rust patch make bzip2 openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel gawk
  elif [[ -x "$(command -v pacman)" ]]; then
    sudo pacman -S --needed --noconfirm base base-devel gawk git libffi libyaml openssl rust zlib
  fi
fi
