#!/bin/sh

# Install or Update Nerd Fonts

if [[ -d "$HOME/.local/share/nerd-fonts" ]]; then
  cd $HOME/.local/share/nerd-fonts
  git pull
  ./install.sh $1
else
  git clone --depth=1 https://github.com/ryanoasis/nerd-fonts $HOME/.local/share/nerd-fonts
  cd $HOME/.local/share/nerd-fonts
  ./install.sh $1
fi
