[metadata]
name = "tmux-sessions"
description = "Switch to tmuxifier or active tmux sessions"
requirements = ["tmuxifier", "tmux"]

[source]
command = 'sh "$HOME/.dotfiles/dot-config/television/cable/scripts/tmux-sessions-source.sh"'
no_sort = true
display = "{split:\t:1}"
output = "{split:\t:2}\t{split:\t:3}"

[keybindings]
enter = "actions:connect"
ctrl-x = ["actions:kill_session", "reload_source"]

[actions.connect]
description = "Connect to selected session"
command = 'sh "$HOME/.dotfiles/dot-config/television/cable/scripts/tmux-sessions-connect.sh" "{split:\t:2}" "{split:\t:3}"'
mode = "execute"

[actions.kill_session]
description = "Kill selected tmux session"
command = 'sh "$HOME/.dotfiles/dot-config/television/cable/scripts/tmux-sessions-kill.sh" "{split:\t:2}"'
mode = "fork"
