[metadata]
name = "tmux-windows"
description = "Add a tmuxifier window to the current tmux session"
requirements = ["tmuxifier", "tmux"]

[source]
command = 'sh "$HOME/.dotfiles/dot-config/television/cable/scripts/tmux-windows-source.sh"'
no_sort = true
display = "{split:\t:0}"
output = "{split:\t:1}"

[actions.load_window]
description = "Load selected tmuxifier window"
command = 'bash "$HOME/.dotfiles/dot-config/television/cable/scripts/tmux-windows-load.sh" "{split:\t:1}"'
mode = "execute"

[keybindings]
enter = "actions:load_window"
