#! /usr/bin/env bash

sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf swap ffmpeg-free ffmpeg --allowerasing

sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld

sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld

sudo dnf update @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

sudo dnf install flac intel-media-driver lame opus-tools vorbis-tools
