#!/bin/sh

# Base Requirements
sudo pacman -S --noconfirm --needed base
sudo pacman -S --noconfirm --needed base-devel

# AUR Helper
source ./yay

# Codecs
sudo pacman -S --noconfirm --needed gst-libav gst-plugins-bad gst-plugins-good gst-plugins-ugly flac opus-tools vorbis-tools

# File Extractors
sudo pacman -S --noconfirm --needed unace cabextract p7zip uncompress unlzma unrar unxz unzip 

# Flatpak
sudo pacman -S --noconfirm --needed flatpak

# Intel Drivers
sudo pacman -S --noconfirm --needed intel-media-driver intel-media-sdk

# Hyprland
sudo pacman -S --noconfirm --needed hyprland hyprpaper hyprlock

# Sway Packages
sudo pacman -S --noconfirm --needed sway swaybg swayidle swaylock

# General Desktop Packages
sudo pacman -S --noconfirm --needed alacritty foot kitty mako waybar wezterm wofi

# General Packages
sudo pacman -S --noconfirm --needed abcde atool bash-completion bash-langage-server bat bat-extras distrobox eza fd ffmpegthumbnailer fzf github-cli glow gvfs gvfs-afc gvfs-mtp gvfs-smb highlight htop hunspell hunspell-en_us imagemagick jq just lazygit mediainfo mpc mpd mpv ncmpcpp neofetch neovim poppler ripgrep starship tmux tree-sitter ueberzug unarchiver vifm xdg-user-dirs-gtk yt-dlp zellij zoxide
