#!/bin/sh

sudo pacman -S --noconfirm --needed zram-generator

echo "[zram0]
zram-size = ram / 2
compression-algorithm = zstd" | sudo tee /etc/systemd/zram-generator.conf

sudo systemctl daemon-reload
sudo systemctl start /dev/zram0
