#! /bin/sh

# Install Common Dependancies

# Install Common Devel Dependencies
vso install autoconf patch build-essential rustc libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev

# Install Personal Tools & Dependencies
vso install abcde neovim tmux

uget bat bottom eza fd fzf lazygit sesh starship tmp zellij zoxide

# Install NerdFonts
source $HOME/.dotfiles/installers/nerd-fonts Hack

source $HOME/.bashrc
