#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &

# Set Desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Set Desktop Layouts
bsp-layout set 1 tall
bsp-layout set 2 tall
bsp-layout set 3 tall
bsp-layout set 4 tall
bsp-layout set 5 tall
bsp-layout set 6 tall
bsp-layout set 7 tall
bsp-layout set 8 tall
bsp-layout set 9 tall

# Window Borders/Gaps
bspc config border_width         6
bspc config window_gap          20
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# Colors
bspc config normal_border_color	   "#2e3440"
bspc config active_border_color	   "#a3be8c"
bspc config focused_border_color   "#a3be8c"
bspc config presel_feedback_color  "#5e81ac"
bspc config urgent_border_color    "#bf616a"

# Application Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
