#!/bin/sh

# Check for Git
if [[ ! -x "$(command -v git)" ]]
then
  echo 'Error: git is not installed.' >&2
  exit 1
fi

# Check for Stow
if [[ ! -x "$(command -v stow)" ]]
then
  echo 'Error: stow is not installed.' >&2
  exit 1
fi

# Clone Dotfiles
if [[ ! -d $HOME/.dotfiles ]]
then
  git clone git@gitlab.com:nclundell/dotfiles $HOME/.dotfiles || { echo 'Error: Could not clone dotfiles.'; exit 1; }
fi

# Stow Dotfiles
stow --dotfiles $HOME/.dotfiles

# Re-source Bash
source $HOME/.bashrc
