## Layout

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

## Lint

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

## Metrics

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

## Naming

Naming/BinaryOperatorParameterName:
  Enabled: false

 ## Style

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false

Style/PreferredHashMethods:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets
