#!/bin/sh

# Add RPMFusion Repos
sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Install Basics
sudo dnf -y install intel-media-driver intel-mediasdk handbrake

distrobox-export --app ghb

source $HOME/.bashrc
