#!/bin/sh

# Add RPMFusion Repos
sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Install Devel Packages
sudo dnf install -y bzip2 g++ gcc git make neovim patch ripgrep rust tmux
sudo dnf install -y gdbm-devel libffi-devel libyaml-devel ncurses-devel openssl-devel readline-devel zlib-devel

# Install Media Packages
sudo dnf -y install abcde flac handbrake-gui intel-media-driver intel-mediasdk lame opus-tools vorbis-tools

# Install RTX
source $HOME/.dotfiles/installers/rtx

# Install Lazygit
source $HOME/.dotfiles/installers/lazygit

# Install Starship
source $HOME/.dotfiles/installers/starship

# Install NerdFonts
source $HOME/.dotfiles/installers/nerd-fonts Hack

source $HOME/.bashrc
