#! /bin/sh

# Install Common Dependancies
sudo zypper -n in 7zip autoconf automake bzip2 gcc gcc-c++ git htop intltool make neovim opi patch ripgrep stow tmux unrar unzip

# Install Common Devel Dependancies
sudo zypper -n in gdbm-devel libopenssl-devel libyaml-devel libffi-devel ncurses-devel postgresql-devel readline-devel zlib-devel

# Install Personal Dependancies
sudo zypper -n in abcde flac intel-media-driver libmfx opus-tools vorbis-tools 

# Install Codecs
opi -n codecs

# Install RTX
source $HOME/.dotfiles/installers/rtx

# Install Lazygit
source $HOME/.dotfiles/installers/lazygit

# Install NerdFonts
source $HOME/.dotfiles/installers/nerd-fonts Hack

source $HOME/.bashrc
