#! /bin/sh

# Install Common Dependancies
sudo zypper -n in 7zip autoconf automake bzip2 gcc gcc-c++ git intltool make opi patch unrar unzip

# Install Common Devel Dependencies
sudo zypper -n in gdbm-devel libopenssl-devel libyaml-devel libffi-devel ncurses-devel postgresql-devel readline-devel zlib-devel

# Install Personal Dependencies
sudo zypper -n in flac intel-media-driver libmfx opus-tools vorbis-tools

# Install Personal Tools
sudo zypper in abcde alacritty bat bottom fd fzf neovim starship tmux yazi zellij

install lazygit sesh tpm

# Install NerdFonts
source $HOME/.dotfiles/installers/nerd-fonts Hack

source $HOME/.bashrc
