#!/bin/sh

# Install or Update ASDF
if [[ -d "$HOME/.local/share/asdf" ]]; then
  cd $HOME/.local/share/asdf
  git pull
else
  git clone https://github.com/asdf-vm/asdf.git ~/.local/share/asdf
  asdf plugin add neovim
  asdf plugin add python
  asdf plugin add ruby
fi

if [[ ! -d "$HOME/.config/asdf" ]]; then
  cd $HOME/.dotfiles
  stow asdf
fi
