#!/bin/bash

# Install or Update lazygit

mkdir -p $HOME/.local/bin

OS=$(uname -s)
case $OS in
  Linux) OS=linux ;;
  Darwin) OS=macos ;;
esac

GITHUB_LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/MordechaiHadad/bob/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
GITHUB_FILE="bob-${OS}-x86_64.zip"
GITHUB_URL="https://github.com/MordechaiHadad/bob/releases/download/${GITHUB_LATEST_VERSION}/${GITHUB_FILE}"

# install/update the local binary
mkdir tmp
curl -L -o tmp/bob.zip $GITHUB_URL
cd tmp
unzip bob.zip
mv -f bob $HOME/.local/bin
cd ..
rm -r tmp
