#!/bin/sh

# Install or Update dblab

mkdir -p $HOME/.local/bin

OS=$(uname -s)
case $OS in
  Linux) OS=linux ;;
  Darwin) OS=darwin ;;
esac

ARCH=$(uname -m)
case $ARCH in
  i386|i686|x86_64) ARCH=amd64 ;;
  aarch64*) ARCH=arm64 ;;
esac

GITHUB_LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/danvergara/dblab/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
GITHUB_FILE="dblab_${GITHUB_LATEST_VERSION//v/}_${OS}_${ARCH}.tar.gz"
GITHUB_URL="https://github.com/danvergara/dblab/releases/download/${GITHUB_LATEST_VERSION}/${GITHUB_FILE}"

# install/update the local binary
mkdir tmp
curl -L -o tmp/dblab.tar.gz $GITHUB_URL
cd tmp
tar xzvf dblab.tar.gz
mv -f dblab $HOME/.local/bin
cd ..
rm -r tmp
