#!/bin/sh

# Install Essentials
sudo dnf -y install g++ git stow starship

# Clone Dotfiles
if [[ ! -d $HOME/.dotfiles ]]
then
  git clone git@gitlab.com:nclundell/dotfiles $HOME/.dotfiles
fi

# Setup Configs
cd $HOME/.dotfiles
stow abcde
stow alacritty
stow asdf
stow dnf
stow git
stow mpd
stow ncmpcpp
stow nvim
stow rubocop
stow scripts

# Setup Shell
if [[ -f $HOME/.bashrc ]]
then
mv $HOME/.bashrc $HOME/.bashrc.bak
fi

stow shell

source $HOME/.bashrc

# Add RPMFusion Repos
sudo dnf -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Add Brave Browser Repo
sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

# Add ProtonVPN Repo
sudo dnf -y install https://protonvpn.com/download/protonvpn-stable-release-1.0.1-1.noarch.rpm

# Install Basics
sudo dnf -y install abcde brave-browser protonvpn telegram-desktop steam lutris discord

# Install Gnome Stuff
sudo dnf -y install celluloid chrome-gnome-shell gnome-extensions-app gnome-shell-extension-appindicator gnome-tweaks lollypop

# Add Flathub
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
