#!/bin/sh

# Check for Flatpak
if [[ ! -x "$(command -v flatpak)" ]]
then
  echo 'Error: flatpak is not installed.' >&2
  exit 1
fi

# Add Flathub
# flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install Flatpaks
flatpak install -y flathub io.github.Foldex.AdwSteamGtk                         # AdwSteamGtk
flatpak install -y flathub com.bitwarden.desktop                                # Bitwarden
flatpak install -y flathub com.usebottles.bottles                               # Bottles
flatpak install -y flathub com.brave.Browser                                    # Brave Browser
flatpak install -y flathub org.gnome.Calendar                                   # Calendar (Gnome)
flatpak install -y flathub io.github.celluloid_player.Celluloid                 # Celluloid
flatpak install -y flathub com.gitlab.davem.ClamTk                              # ClamTk
flatpak install -y flathub org.gnome.clocks                                     # Clocks (Gnome)
flatpak install -y flathub com.discordapp.Discord                               # Discord
flatpak install -y flathub org.gnome.baobab                                     # Disk Usage
flatpak install -y flathub org.gnome.SimpleScan                                 # Document Scanner (Gnome)
flatpak install -y flathub org.gnome.Evince                                     # Document Viewer (Gnome)
flatpak install -y flathub com.mattjakeman.ExtensionManager                     # Extension Manager
flatpak install -y flathub org.mozilla.firefox                                  # Firefox Browser
flatpak install -y flathub com.github.tchx84.Flatseal                           # Flatseal
flatpak install -y flathub io.github.giantpinkrobots.flatsweep                  # Flatsweep
flatpak install -y flathub de.haeckerfelix.Fragments                            # Fragments
flatpak install -y flathub com.github.GradienceTeam.Gradience                   # Gradience
flatpak install -y flathub io.gitlab.librewolf-community                        # LibreWolf
flatpak install -y flathub org.gnome.Lollypop                                   # Lollypop
flatpak install -y flathub org.gnome.Loupe                                      # Loupe
flatpak install -y flathub com.makemkv.MakeMKV                                  # MakeMKV
flatpak install -y flathub org.bunkus.mkvtoolnix-gui                            # MKVToolNix Gui
flatpak install -y flathub org.nickvision.tubeconverter                         # Parabolic
flatpak install -y flathub de.haeckerfelix.Shortwave                            # Shortwave
flatpak install -y flathub org.telegram.desktop                                 # Telegram
flatpak install -y flathub com.valvesoftware.Steam                              # Steam
flatpak install -y flathub com.valvesoftware.Steam.CompatibilityTool.Proton     # Steam Proton
flatpak install -y flathub com.valvesoftware.Steam.CompatibilityTool.Proton-GE  # Steam Proton-GE
flatpak install -y flathub org.gnome.Weather                                    # Weather (Gnome)
