#!/bin/bash

# Install or Update gobang

mkdir -p $HOME/.local/bin

OS=$(uname -s)
case $OS in
  Linux) OS=unknown-linux-musl ;;
  Darwin) OS=apple-darwin ;;
esac

GITHUB_LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/TaKO8Ki/gobang/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
GITHUB_FILE_NAME="gobang-${GITHUB_LATEST_VERSION//v/}-x86_64-${OS}"
GITHUB_URL="https://github.com/TaKO8Ki/gobang/releases/download/${GITHUB_LATEST_VERSION}/${GITHUB_FILE_NAME}.tar.gz"

# install/update the local binary
mkdir tmp
curl -L -o tmp/gobang.tar.gz $GITHUB_URL
cd tmp
tar xzvf gobang.tar.gz
cd ${GITHUB_FILE_NAME}
mv -f gobang $HOME/.local/bin
cd ../..
rm -r tmp
