#!/bin/sh

# Install or Update Lazygit https://github.com/jorgerojas26/lazysql

mkdir -p $HOME/.local/bin

OS=$(uname -s)
case $OS in
  Linux) OS=Linux ;;
  Darwin) OS=Darwin ;;
esac

ARCH=$(uname -m)
case $ARCH in
  x86_64) ARCH=x86_64 ;;
  aarch64*) ARCH=arm64 ;;
esac

GITHUB_LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/jorgerojas26/lazysql/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
GITHUB_FILE="lazysql_${OS}_${ARCH}.tar.gz"
GITHUB_URL="https://github.com/jorgerojas26/lazysql/releases/download/${GITHUB_LATEST_VERSION}/${GITHUB_FILE}"

# install/update the local binary
mkdir tmp
curl -L -o tmp/lazysql.tar.gz $GITHUB_URL
cd tmp
tar xzvf lazysql.tar.gz
mv -f lazysql $HOME/.local/bin
cd ..
rm -r tmp
