#!/bin/sh

if ! command -v asdf version &> /dev/null
then
  printf "\nInstalling ASDF...\n\n"
  ./asdf
fi

printf "\nAdding ASDF Neovim Plugin...\n\n"
asdf plugin add neovim

printf "\nInstalling 'nightly' and 'stable' versions...\n\n"
asdf install neovim nightly
asdf install neovim stable

printf "\nGlobal version set to 'nightly'"
asdf global neovim nightly

if [[ ! -d "$HOME/.config/nvim" ]]; then
  printf "\n\nLink to Neovim config..."
  cd $HOME/.dotfiles
  stow nvim
fi
