#!/bin/sh

# Install or Update RTX https://github.com/jdx/rtx

mkdir -p $HOME/.local/bin

OS=$(uname -s)
case $OS in
  Linux) OS=linux ;;
  Darwin) OS=macos ;;
esac

ARCH=$(uname -m)
case $ARCH in
  x86_64) ARCH=x64 ;;
  aarch64*) ARCH=arm64 ;;
esac

curl https://rtx.pub/rtx-latest-${OS}-${ARCH} > $HOME/.local/bin/rtx
cd $HOME/.local/bin
chmod a+x rtx
