#!/bin/sh

# Install Essentials
sudo zypper -n install curl git stow

# Clone Dotfiles
if [[ ! -d $HOME/.dotfiles ]]
then
  git clone git@gitlab.com:nclundell/dotfiles $HOME/.dotfiles
fi

# Setup Configs
cd $HOME/.dotfiles
stow abcde
stow alacritty
stow asdf
stow git
stow mpd
stow ncmpcpp
stow nvim
stow rubocop
stow scripts

# Setup Shell
if [[ -f $HOME/.bashrc ]]
then
mv $HOME/.bashrc $HOME/.bashrc.bak
fi

stow shell

source $HOME/.bashrc

# Install ASDF
source $HOME/.dotfiles/installers/asdf

# Install Lazygit
source $HOME/.dotfiles/installers/lazygit

# Add Packman and Install Codecs
sudo zypper addrepo -cfp 90 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/' packman
sudo zypper refresh
sudo zypper dist-upgrade --from packman --allow-vendor-change
sudo zypper -n install --from packman ffmpeg gstreamer-plugins-{good,bad,ugly,libav} libavcodec-full

# Add Brave Browser
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
sudo zypper addrepo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
sudo zypper -n install brave-browser

# Install Basics
sudo zypper -n install abcde alacritty discord fetchmsttfonts firefox gamemoded lutris makemkv mangohud mkvtoolnix-gui mpd ncmpcpp neovim opus-tools protonvpn-cli protonvpn-gui ripgrep starship steam telegram-desktop vorbis-tools youtube-dl

# Install Qtile
if [[ -d $HOME/.config/qtile ]]
then
  rm -rf $HOME/.config/qtile
fi

stow qtile

# Add Flathub
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install NerdFonts
source $HOME/.dotfiles/installers/nerd-fonts Hack

# User Sudo
sudo gpasswd -a $USER wheel
sudo visudo
su -c reboot
