#!/bin/sh

# Check for Flatpak
if [[ ! -x "$(command -v flatpak)" ]]
then
  echo 'Error: flatpak is not installed.' >&2
  exit 1
fi

# Add Flathub
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Gnome Flatpaks
flatpak install -y flathub org.gnome.Calendar                       # Calendar
flatpak install -y flathub org.gnome.Calculator                     # Calculator
flatpak install -y flathub io.github.celluloid_player.Celluloid     # Celluloid
flatpak install -y flathub org.gnome.clocks                         # Clocks
flatpak install -y flathub org.gnome.SimpleScan                     # Document Scanner
flatpak install -y flathub org.gnome.Evince                         # Document Viewer
flatpak install -y flathub org.gnome.Lollypop                       # Lollypop
flatpak install -y flathub org.gnome.Loupe                          # Loupe
flatpak install -y flathub org.gnome.Weather                        # Weather
