#!/bin/sh

# Check for Flatpak
if [[ ! -x "$(command -v flatpak)" ]]
then
  echo 'Error: flatpak is not installed.' >&2
  exit 1
fi

# Add Flathub
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install Flatpaks
flatpak install -y flathub io.github.Foldex.AdwSteamGtk                         # AdwSteamGtk
flatpak install -y flathub com.usebottles.bottles                               # Bottles
flatpak install -y flathub io.github.dvlv.boxbuddyrs                            # BoxBuddy
flatpak install -y flathub com.brave.Browser                                    # Brave Browser
flatpak install -y flathub com.gitlab.davem.ClamTk                              # ClamTk
flatpak install -y flathub cafe.avery.Delfin                                    # Delfin (Jellyfin)
flatpak install -y flathub com.discordapp.Discord                               # Discord
flatpak install -y flathub org.mozilla.firefox                                  # Firefox Browser
flatpak install -y flathub com.github.tchx84.Flatseal                           # Flatseal
flatpak install -y flathub de.haeckerfelix.Fragments                            # Fragments
flatpak install -y flathub net.lutris.Lutris                                    # Lutris
flatpak install -y flathub com.makemkv.MakeMKV                                  # MakeMKV
flatpak install -y flathub io.missioncenter.MissionCenter                       # MissionCenter
flatpak install -y flathub org.bunkus.mkvtoolnix-gui                            # MKVToolNix Gui
flatpak install -y md.obsidian.Obsidian                                         # Obsidian
flatpak install -y flathub org.nickvision.tubeconverter                         # Parabolic
flatpak install -y flathub com.vysp3r.ProtonPlus                                # Proton Plus
# flatpak install -y flathub net.nokyan.Resources                                 # Resources
flatpak install -y flathub com.valvesoftware.Steam                              # Steam
flatpak install -y com.valvesoftware.Steam.Utility.steamtinkerlaunch            # SteamTinkerLaunch
flatpak install -y flathub org.telegram.desktop                                 # Telegram
flatpak install -y flathub io.github.flattool.Warehouse                         # Warehouse

# Required Extras
flatpak install -y adw-gtk3
flatpak install -y adw-gtk3-dark

# Setup SteamTinkerLaunch
# flatpak run --command=sh com.valvesoftware.Steam
# steamtinkerlaunch compat add
# exit
