#! /usr/bin/env bash

sudo pacman -S --noconfirm --needed lshw jq

vendor_check=$(sudo lshw -json -c display | jq '.[0]["vendor"]')

if [[ $vendor_check == *"Advanced Micro Devices"* ]]; then
  echo "Installing AMD drivers..."
  sudo pacman -S --noconfirm --needed mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon libva-mesa-driver libva-utils
elif [[ $vendor_check == *"Intel"* ]]; then
  echo "Installing Intel drivers..."
  sudo pacman -S --noconfirm --needed intel-media-driver mesa lib32-mesa vulkan-intel lib32-vulkan-intel lib32-meda-driver libva-utils
else
  sudo pacman -S --noconfirm --needed mesa lib32-mesa lib32-meda-driver libva-utils
fi

