#! /usr/bin/env bash

sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed lshw jq

vendor_check=$(sudo lshw -json -c display | jq '.[0]["vendor"]')

if [[ $vendor_check == *"Advanced Micro Devices"* ]]; then
  echo "Installing AMD drivers..."
  sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon libva-utils
elif [[ $vendor_check == *"Intel"* ]]; then
  echo "Installing Intel drivers..."
  sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed mesa lib32-mesa vulkan-intel lib32-vulkan-intel libva-utils intel-media-driver
else
  sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed mesa lib32-mesa libva-utils
fi

