#! /usr/bin/env bash

sudo pacman -S --noconfirm --needed network-manager-applet networkmanager networkmanager-openvpn networkmanager-openconnect wireguard-tools

sudo systemctl enable --now NetworkManager
