#!/bin/sh

sudo pacman -S --noconfirm --needed snapper snap-pac grub-btrfs

sudo umount /.snapshots

sudo rm -r /.snapshots

sudo snapper -c root create-config /

sudo mount -a

sudo systemctl enable --now grub-btrfsd

echo "Add the following to the HOOKS array in /etc/mkinitcpio.conf"
echo "grub-btrfs-overlayfs"
echo "Then regenerate the initramfs images with:"
echo "mkinitcpio -p"
