#! /usr/bin/env bash

sudo pacman -S --noconfirm --needed snapper

sudo umount /.snapshots

sudo rm -r /.snapshots

sudo snapper -c root create-config /

sudo btrfs subvolume delete /.snapshots

sudo mkdir /.snapshots

sudo chmod 750 /.snapshots

sudo chown :wheel /.snapshots

sudo mount -a

if [[ ! -x "$(command -v grub-mkconfig)" ]]; then
  sudo pacman -S --noconfirm --needed grub-btrfs inotify-tools

  if ! $(grep -qe "^HOOKS=.*grub-btrfs-overlayfs" /etc/mkinitcpio.conf); then
    sudo sed -re 's/(^HOOKS=[\"|(][^")]+)/\1 grub-btrfs-overlayfs/gi' -i /etc/mkinitcpio.conf
    sudo mkinitcpio -P
  fi

  sudo systemctl enable --now grub-btrfsd

  sudo grub-mkconfig -o /boot/grub/grub.cfg
fi

sudo pacman -S --noconfirm --needed snap-pac
