#! /bin/bash

sudo pacman -S --noconfirm --needed grub-btrfs inotify-tools snapper

sudo umount /.snapshots

sudo rm -r /.snapshots

sudo snapper -c root create-config /

sudo btrfs subvolume delete /.snapshots

sudo mkdir /.snapshots

sudo chmod 750 /.snapshots

sudo chown :wheel /.snapshots

sudo mount -a

cat /etc/fstab

sudo pacman -S --noconfirm --needed snap-pac

sudo systemctl enable --now grub-btrfsd

sudo grub-mkconfig -o /boot/grub/grub.cfg

echo "Add grub-btrfs-overlayfs to HOOKS array in /etc/mkinitcpio.conf"
echo "Run sudo mkinitcpio -P to regenerate initramfs"
