#!/bin/sh

# Base
sudo pacman -S --noconfirm --needed rofi-wayland sway sway-contrib swaybg swayidle swayimg swaylock swaync waybar wezterm

# Multimedia
source ./codecs
sudo pacman -S --noconfirm --needed mpd mpv ncmpcpp

# Get CLI Tools
source ./tools-cli
