#! /usr/bin/env bash

# Base
sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed rofi-wayland sway sway-contrib swaybg swayidle swayimg swaylock swaync waybar wezterm

# Multimedia
source ./codecs
sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed mpd mpv ncmpcpp

# Get CLI Tools
source ./tools-cli
