#!/bin/sh

sudo pacman -S --noconfirm --needed bat bottom cabextract eza fd fzf github-cli gitui glow jq just lazygit neovim p7zip poppler ripgrep starship tmux unace unrar unzip xz yazi zellij zoxide
