#! /usr/bin/env bash

#Apps
sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed btrfs-assistant firefox ghostty octopi

# Deps
sudo pacman -S --config $HOME/.dotfiles/dot-config/pacman/pacman.conf --noconfirm --needed hunspell-en_us  speech-dispatcher

