#!/bin/sh

sudo pacman -S --noconfirm --needed bat bottom cabextract curl eza fd fzf github-cli gitui glow jq just lazygit neovim p7zip poppler ripgrep starship tmux udiskie unace unrar unzip wget xz yazi zellij zoxide

sudo pacman -S --noconfirm --needed nerd-fonts noto-fonts noto-fonts-cjk noto-fonts-emoji

source $HOME/.dotfiles/dot-local/installers/distros/arch/yay
