#! /usr/bin/env bash

if [[ ! -x "$(command -v yay)" ]]; then
  source $HOME/.dotfiles/dot-local/installers/distros/arch/yay
fi

sudo pacman -S --noconfirm --needed ghostty

yay -S btrfs-assistant octopi
