#!/bin/sh

# Install or Update Starship https://github.com/starship/starship

mkdir -p $HOME/.local/bin

OS=$(uname -s)
case $OS in
  Linux) OS=unknown-linux-musl ;;
  Darwin) OS=apple-darwin ;;
esac

ARCH=$(uname -m)
case $ARCH in
  x86_64) ARCH=x86_64 ;;
  aarch64*) ARCH=aarch64 ;;
esac

GITHUB_LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/starship/starship/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
GITHUB_FILE="starship-${ARCH}-${OS}.tar.gz"
GITHUB_URL="https://github.com/starship/starship/releases/download/${GITHUB_LATEST_VERSION}/${GITHUB_FILE}"

# install/update the local binary
mkdir tmp
curl -L -o tmp/starship.tar.gz $GITHUB_URL
cd tmp
tar xzvf starship.tar.gz
mv -f starship $HOME/.local/bin
cd ..
rm -r tmp
