#!/bin/sh

# Install or Update Zellij https://github.com/zellij-org/zellij

mkdir -p $HOME/.local/bin

OS=$(uname -s)
case $OS in
  Linux) OS=unknown-linux-musl ;;
  Darwin) OS=apple-darwin ;;
esac

ARCH=$(uname -m)
case $ARCH in
  x86_64) ARCH=x86_64 ;;
  arm64) ARCH=aarch64 ;;
esac

GITHUB_LATEST_VERSION=$(curl -L -s -H 'Accept: application/json' https://github.com/zellij-org/zellij/releases/latest | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
GITHUB_FILE="zellij-${ARCH}-${OS}.tar.gz"
GITHUB_URL="https://github.com/zellij-org/zellij/releases/download/${GITHUB_LATEST_VERSION}/${GITHUB_FILE}"

# install/update the local binary
mkdir tmp
echo $GITHUB_URL
curl -L -o tmp/zellij.tar.gz $GITHUB_URL
cd tmp
tar xzvf zellij.tar.gz
mv -f zellij $HOME/.local/bin
cd ..
rm -r tmp
